# Global configuration file for Supabase CLI.
# This file forces the use of cloud Supabase instead of local development

[api]
enabled = false
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
enabled = false
port = 54322
major_version = 15

[studio]
enabled = false
port = 54323
api_url = "http://127.0.0.1:54321"

[auth]
enabled = false
port = 54324
site_url = "http://127.0.0.1:3000"

[storage]
enabled = false
port = 54325

[edge_runtime]
enabled = false
port = 54326

# Force cloud connection
[project_ref]
ref = "vetufvhzmawjbsumtplq"

# Environment settings
[environments.production]
ref = "vetufvhzmawjbsumtplq"
url = "https://vetufvhzmawjbsumtplq.supabase.co"
